const POKEMONS_REDUCER_TYPES = {
  FETCH_POKEMONS_START: "FETCH_POKEMONS_START",
  FETCH_POKEMONS_SUCCESS: "FETCH_POKEMONS_SUCCESS",
  FETCH_POKEMONS_FAILED: "FETCH_POKEMONS_FAILED",
  FETCH_POKEMON_START: "FETCH_POKEMON_START",
  FETCH_POKEMON_SUCCESS: "FETCH_POKEMON_SUCCESS",
  FETCH_POKEMON_FAILED: "FETCH_POKEMON_FAILED",
  SET_PAGE: "SET_PAGE",
};

export default POKEMONS_REDUCER_TYPES;
